# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rota._gen.rota.v1 import rota_pb2 as rota_dot_v1_dot_rota__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rota/v1/rota_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrokerStub:
    """─────────────────────────────────────────────────────────────────────────────
    Services
    ─────────────────────────────────────────────────────────────────────────────

    Broker is the data plane: publishing work and the bidirectional Work stream
    over which consumers lease, ack/nack, extend, and complete messages.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/rota.v1.Broker/Publish',
                request_serializer=rota_dot_v1_dot_rota__pb2.PublishRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.PublishResponse.FromString,
                _registered_method=True)
        self.PublishBatch = channel.unary_unary(
                '/rota.v1.Broker/PublishBatch',
                request_serializer=rota_dot_v1_dot_rota__pb2.PublishBatchRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.PublishBatchResponse.FromString,
                _registered_method=True)
        self.Work = channel.stream_stream(
                '/rota.v1.Broker/Work',
                request_serializer=rota_dot_v1_dot_rota__pb2.WorkClientMsg.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.WorkServerMsg.FromString,
                _registered_method=True)


class BrokerServicer:
    """─────────────────────────────────────────────────────────────────────────────
    Services
    ─────────────────────────────────────────────────────────────────────────────

    Broker is the data plane: publishing work and the bidirectional Work stream
    over which consumers lease, ack/nack, extend, and complete messages.
    """

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Work(self, request_iterator, context):
        """Work is a long-lived bidirectional stream. The client advertises demand
        (credit) and acks/nacks; the server pushes leases and flow-control frames.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.PublishRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.PublishResponse.SerializeToString,
            ),
            'PublishBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishBatch,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.PublishBatchRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.PublishBatchResponse.SerializeToString,
            ),
            'Work': grpc.stream_stream_rpc_method_handler(
                    servicer.Work,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.WorkClientMsg.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.WorkServerMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rota.v1.Broker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rota.v1.Broker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Broker:
    """─────────────────────────────────────────────────────────────────────────────
    Services
    ─────────────────────────────────────────────────────────────────────────────

    Broker is the data plane: publishing work and the bidirectional Work stream
    over which consumers lease, ack/nack, extend, and complete messages.
    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Broker/Publish',
            rota_dot_v1_dot_rota__pb2.PublishRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Broker/PublishBatch',
            rota_dot_v1_dot_rota__pb2.PublishBatchRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.PublishBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Work(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/rota.v1.Broker/Work',
            rota_dot_v1_dot_rota__pb2.WorkClientMsg.SerializeToString,
            rota_dot_v1_dot_rota__pb2.WorkServerMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ControlStub:
    """Control is the control plane: group config + lifecycle, programmable policy
    management, cron, singleton leases, off-stream completion, and introspection.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetGroupConfig = channel.unary_unary(
                '/rota.v1.Control/SetGroupConfig',
                request_serializer=rota_dot_v1_dot_rota__pb2.SetGroupConfigRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.GroupConfig.FromString,
                _registered_method=True)
        self.GetGroupConfig = channel.unary_unary(
                '/rota.v1.Control/GetGroupConfig',
                request_serializer=rota_dot_v1_dot_rota__pb2.GroupRef.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.GroupConfig.FromString,
                _registered_method=True)
        self.PauseGroup = channel.unary_unary(
                '/rota.v1.Control/PauseGroup',
                request_serializer=rota_dot_v1_dot_rota__pb2.GroupRef.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.GroupConfig.FromString,
                _registered_method=True)
        self.ResumeGroup = channel.unary_unary(
                '/rota.v1.Control/ResumeGroup',
                request_serializer=rota_dot_v1_dot_rota__pb2.GroupRef.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.GroupConfig.FromString,
                _registered_method=True)
        self.CancelGroup = channel.unary_unary(
                '/rota.v1.Control/CancelGroup',
                request_serializer=rota_dot_v1_dot_rota__pb2.GroupRef.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.GroupOpResult.FromString,
                _registered_method=True)
        self.PurgeGroup = channel.unary_unary(
                '/rota.v1.Control/PurgeGroup',
                request_serializer=rota_dot_v1_dot_rota__pb2.GroupRef.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.GroupOpResult.FromString,
                _registered_method=True)
        self.ReapGroup = channel.unary_unary(
                '/rota.v1.Control/ReapGroup',
                request_serializer=rota_dot_v1_dot_rota__pb2.GroupRef.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.GroupOpResult.FromString,
                _registered_method=True)
        self.TeardownGroup = channel.unary_unary(
                '/rota.v1.Control/TeardownGroup',
                request_serializer=rota_dot_v1_dot_rota__pb2.TeardownRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.TeardownResult.FromString,
                _registered_method=True)
        self.SetLaneConfig = channel.unary_unary(
                '/rota.v1.Control/SetLaneConfig',
                request_serializer=rota_dot_v1_dot_rota__pb2.SetLaneConfigRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.LaneConfig.FromString,
                _registered_method=True)
        self.PauseLane = channel.unary_unary(
                '/rota.v1.Control/PauseLane',
                request_serializer=rota_dot_v1_dot_rota__pb2.PauseLaneRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.LaneOpResult.FromString,
                _registered_method=True)
        self.ResumeLane = channel.unary_unary(
                '/rota.v1.Control/ResumeLane',
                request_serializer=rota_dot_v1_dot_rota__pb2.LaneRef.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.LaneOpResult.FromString,
                _registered_method=True)
        self.SetPolicy = channel.unary_unary(
                '/rota.v1.Control/SetPolicy',
                request_serializer=rota_dot_v1_dot_rota__pb2.SetPolicyRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.PolicyInfo.FromString,
                _registered_method=True)
        self.GetPolicy = channel.unary_unary(
                '/rota.v1.Control/GetPolicy',
                request_serializer=rota_dot_v1_dot_rota__pb2.LaneRef.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.PolicyInfo.FromString,
                _registered_method=True)
        self.ValidatePolicy = channel.unary_unary(
                '/rota.v1.Control/ValidatePolicy',
                request_serializer=rota_dot_v1_dot_rota__pb2.SetPolicyRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.ValidatePolicyResult.FromString,
                _registered_method=True)
        self.ScheduleCron = channel.unary_unary(
                '/rota.v1.Control/ScheduleCron',
                request_serializer=rota_dot_v1_dot_rota__pb2.ScheduleCronRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.CronInfo.FromString,
                _registered_method=True)
        self.ListCron = channel.unary_unary(
                '/rota.v1.Control/ListCron',
                request_serializer=rota_dot_v1_dot_rota__pb2.ListCronRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.ListCronResponse.FromString,
                _registered_method=True)
        self.DeleteCron = channel.unary_unary(
                '/rota.v1.Control/DeleteCron',
                request_serializer=rota_dot_v1_dot_rota__pb2.CronRef.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.CronOpResult.FromString,
                _registered_method=True)
        self.PauseCron = channel.unary_unary(
                '/rota.v1.Control/PauseCron',
                request_serializer=rota_dot_v1_dot_rota__pb2.CronRef.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.CronInfo.FromString,
                _registered_method=True)
        self.AcquireSingletonLease = channel.unary_unary(
                '/rota.v1.Control/AcquireSingletonLease',
                request_serializer=rota_dot_v1_dot_rota__pb2.AcquireSingletonRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.SingletonLease.FromString,
                _registered_method=True)
        self.RenewSingletonLease = channel.unary_unary(
                '/rota.v1.Control/RenewSingletonLease',
                request_serializer=rota_dot_v1_dot_rota__pb2.RenewSingletonRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.SingletonLease.FromString,
                _registered_method=True)
        self.ReleaseSingletonLease = channel.unary_unary(
                '/rota.v1.Control/ReleaseSingletonLease',
                request_serializer=rota_dot_v1_dot_rota__pb2.ReleaseSingletonRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.SingletonOpResult.FromString,
                _registered_method=True)
        self.CompleteByToken = channel.unary_unary(
                '/rota.v1.Control/CompleteByToken',
                request_serializer=rota_dot_v1_dot_rota__pb2.CompleteByTokenRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.CompleteResult.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/rota.v1.Control/GetStats',
                request_serializer=rota_dot_v1_dot_rota__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.DescribeCluster = channel.unary_unary(
                '/rota.v1.Control/DescribeCluster',
                request_serializer=rota_dot_v1_dot_rota__pb2.DescribeClusterRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.ClusterInfo.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/rota.v1.Control/Health',
                request_serializer=rota_dot_v1_dot_rota__pb2.HealthRequest.SerializeToString,
                response_deserializer=rota_dot_v1_dot_rota__pb2.HealthResponse.FromString,
                _registered_method=True)


class ControlServicer:
    """Control is the control plane: group config + lifecycle, programmable policy
    management, cron, singleton leases, off-stream completion, and introspection.
    """

    def SetGroupConfig(self, request, context):
        """Group configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseGroup(self, request, context):
        """Group lifecycle. Operating on an absent group is a benign no-op.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelGroup(self, request, context):
        """drop READY/DELAYED, drain in-flight
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeGroup(self, request, context):
        """drop everything leasable, keep config
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReapGroup(self, request, context):
        """idle-reap (asserts empty)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TeardownGroup(self, request, context):
        """one call across ALL lanes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLaneConfig(self, request, context):
        """Lane configuration + back-pressure hooks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseLane(self, request, context):
        """stop leasing a lane (circuit breaker hook)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeLane(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPolicy(self, request, context):
        """Programmable policy (hot-reloadable).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePolicy(self, request, context):
        """compile + dry-run, no install
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScheduleCron(self, request, context):
        """Cron (generic recurring publish).
        idempotent on cron_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCron(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCron(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseCron(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireSingletonLease(self, request, context):
        """Singleton leases (generic cluster-wide single-instance coordination).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewSingletonLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseSingletonLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteByToken(self, request, context):
        """Async completion off-stream (twin of the in-stream Complete frame).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Introspection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetGroupConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGroupConfig,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.SetGroupConfigRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.GroupConfig.SerializeToString,
            ),
            'GetGroupConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupConfig,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.GroupRef.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.GroupConfig.SerializeToString,
            ),
            'PauseGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseGroup,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.GroupRef.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.GroupConfig.SerializeToString,
            ),
            'ResumeGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeGroup,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.GroupRef.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.GroupConfig.SerializeToString,
            ),
            'CancelGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelGroup,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.GroupRef.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.GroupOpResult.SerializeToString,
            ),
            'PurgeGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeGroup,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.GroupRef.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.GroupOpResult.SerializeToString,
            ),
            'ReapGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.ReapGroup,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.GroupRef.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.GroupOpResult.SerializeToString,
            ),
            'TeardownGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.TeardownGroup,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.TeardownRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.TeardownResult.SerializeToString,
            ),
            'SetLaneConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLaneConfig,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.SetLaneConfigRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.LaneConfig.SerializeToString,
            ),
            'PauseLane': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseLane,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.PauseLaneRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.LaneOpResult.SerializeToString,
            ),
            'ResumeLane': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeLane,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.LaneRef.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.LaneOpResult.SerializeToString,
            ),
            'SetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPolicy,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.SetPolicyRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.PolicyInfo.SerializeToString,
            ),
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.LaneRef.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.PolicyInfo.SerializeToString,
            ),
            'ValidatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePolicy,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.SetPolicyRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.ValidatePolicyResult.SerializeToString,
            ),
            'ScheduleCron': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleCron,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.ScheduleCronRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.CronInfo.SerializeToString,
            ),
            'ListCron': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCron,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.ListCronRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.ListCronResponse.SerializeToString,
            ),
            'DeleteCron': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCron,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.CronRef.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.CronOpResult.SerializeToString,
            ),
            'PauseCron': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseCron,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.CronRef.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.CronInfo.SerializeToString,
            ),
            'AcquireSingletonLease': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireSingletonLease,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.AcquireSingletonRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.SingletonLease.SerializeToString,
            ),
            'RenewSingletonLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewSingletonLease,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.RenewSingletonRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.SingletonLease.SerializeToString,
            ),
            'ReleaseSingletonLease': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseSingletonLease,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.ReleaseSingletonRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.SingletonOpResult.SerializeToString,
            ),
            'CompleteByToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteByToken,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.CompleteByTokenRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.CompleteResult.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.GetStatsRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.StatsResponse.SerializeToString,
            ),
            'DescribeCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeCluster,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.DescribeClusterRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.ClusterInfo.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=rota_dot_v1_dot_rota__pb2.HealthRequest.FromString,
                    response_serializer=rota_dot_v1_dot_rota__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rota.v1.Control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rota.v1.Control', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Control:
    """Control is the control plane: group config + lifecycle, programmable policy
    management, cron, singleton leases, off-stream completion, and introspection.
    """

    @staticmethod
    def SetGroupConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/SetGroupConfig',
            rota_dot_v1_dot_rota__pb2.SetGroupConfigRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.GroupConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/GetGroupConfig',
            rota_dot_v1_dot_rota__pb2.GroupRef.SerializeToString,
            rota_dot_v1_dot_rota__pb2.GroupConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/PauseGroup',
            rota_dot_v1_dot_rota__pb2.GroupRef.SerializeToString,
            rota_dot_v1_dot_rota__pb2.GroupConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/ResumeGroup',
            rota_dot_v1_dot_rota__pb2.GroupRef.SerializeToString,
            rota_dot_v1_dot_rota__pb2.GroupConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/CancelGroup',
            rota_dot_v1_dot_rota__pb2.GroupRef.SerializeToString,
            rota_dot_v1_dot_rota__pb2.GroupOpResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurgeGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/PurgeGroup',
            rota_dot_v1_dot_rota__pb2.GroupRef.SerializeToString,
            rota_dot_v1_dot_rota__pb2.GroupOpResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReapGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/ReapGroup',
            rota_dot_v1_dot_rota__pb2.GroupRef.SerializeToString,
            rota_dot_v1_dot_rota__pb2.GroupOpResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TeardownGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/TeardownGroup',
            rota_dot_v1_dot_rota__pb2.TeardownRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.TeardownResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLaneConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/SetLaneConfig',
            rota_dot_v1_dot_rota__pb2.SetLaneConfigRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.LaneConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseLane(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/PauseLane',
            rota_dot_v1_dot_rota__pb2.PauseLaneRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.LaneOpResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeLane(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/ResumeLane',
            rota_dot_v1_dot_rota__pb2.LaneRef.SerializeToString,
            rota_dot_v1_dot_rota__pb2.LaneOpResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/SetPolicy',
            rota_dot_v1_dot_rota__pb2.SetPolicyRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.PolicyInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/GetPolicy',
            rota_dot_v1_dot_rota__pb2.LaneRef.SerializeToString,
            rota_dot_v1_dot_rota__pb2.PolicyInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/ValidatePolicy',
            rota_dot_v1_dot_rota__pb2.SetPolicyRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.ValidatePolicyResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScheduleCron(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/ScheduleCron',
            rota_dot_v1_dot_rota__pb2.ScheduleCronRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.CronInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCron(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/ListCron',
            rota_dot_v1_dot_rota__pb2.ListCronRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.ListCronResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCron(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/DeleteCron',
            rota_dot_v1_dot_rota__pb2.CronRef.SerializeToString,
            rota_dot_v1_dot_rota__pb2.CronOpResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseCron(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/PauseCron',
            rota_dot_v1_dot_rota__pb2.CronRef.SerializeToString,
            rota_dot_v1_dot_rota__pb2.CronInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquireSingletonLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/AcquireSingletonLease',
            rota_dot_v1_dot_rota__pb2.AcquireSingletonRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.SingletonLease.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewSingletonLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/RenewSingletonLease',
            rota_dot_v1_dot_rota__pb2.RenewSingletonRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.SingletonLease.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseSingletonLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/ReleaseSingletonLease',
            rota_dot_v1_dot_rota__pb2.ReleaseSingletonRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.SingletonOpResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteByToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/CompleteByToken',
            rota_dot_v1_dot_rota__pb2.CompleteByTokenRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.CompleteResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/GetStats',
            rota_dot_v1_dot_rota__pb2.GetStatsRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/DescribeCluster',
            rota_dot_v1_dot_rota__pb2.DescribeClusterRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.ClusterInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rota.v1.Control/Health',
            rota_dot_v1_dot_rota__pb2.HealthRequest.SerializeToString,
            rota_dot_v1_dot_rota__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
